[package]
name = "Bandit"
version = "0.1.0"
authors = ["Emile-Aquila"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand_distr = "0.4.3"
rand = "0.8.5"
plotters = "0.3.3"